# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4855d3e446085747057220021626b0e6"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "LS same day delivery staging"
handle = "ls-same-day-delivery-staging"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "for-ls-app-testing.myshopify.com"
include_config_on_deploy = true
